// examples/nextjs/components/BrokenButton.jsx
'use client'

export default function BrokenButton() {
  return (
    <button
      style={{
        padding: '0.75rem 1rem',
        fontSize: '1rem',
        cursor: 'pointer',
        backgroundColor: '#9333ea',
        color: '#fff',
        border: 'none',
        borderRadius: 6,
        fontWeight: 600,
      }}
      onClick={() => { throw new Error('Deep error!') }}
    >
      Deep Error
    </button>
  )
}

// examples/sveltekit/src/lib/components/BrokenButton.svelte
<script>
  const crash = () => { throw new Error('Deep error!') }
</script>

<button
  style="padding: 0.75rem 1rem; font-size: 1rem; cursor: pointer;
         background-color: #9333ea; color: #fff; border: none;
         border-radius: 6px; font-weight: 600;"
  onclick={crash}
>
  Deep Error
</button>
