// examples/nextjs/components/HydrationMismatch.jsx
'use client'

export default function HydrationMismatch() {
  const isServer = typeof window === 'undefined'
  return (
    <button
      style={{
        padding: '0.75rem 1rem',
        fontSize: '1rem',
        cursor: 'pointer',
        backgroundColor: '#06b6d4',
        color: '#fff',
        border: 'none',
        borderRadius: 6,
        fontWeight: 600,
      }}
    >
      Hydration: {isServer ? 'SERVER' : 'CLIENT'}
    </button>
  )
}

// examples/sveltekit/src/lib/components/HydrationMismatch.svelte
<script>
  import { browser } from '$app/environment'
</script>

<button
  style="padding: 0.75rem 1rem; font-size: 1rem; cursor: pointer;
         background-color: #06b6d4; color: #fff; border: none;
         border-radius: 6px; font-weight: 600;"
>
  Hydration: {browser ? 'CLIENT' : 'SERVER'}
</button>
