// examples/sveltekit/src/lib/components/Leaf.svelte
<script>
  let { node, depth } = $props()
</script>

<div style="padding-left: {depth * 16}px;">
  <span style="color: {depth === 0 ? '#9333ea' : '#555'};">
    {#if depth > 0}‣ {/if}{node.label}
  </span>
  {#each node.children as child, i}
    <svelte:self node={child} depth={depth + 1} />
  {/each}
</div>

// examples/nextjs/components/Leaf.jsx
'use client'

export default function Leaf({ node, depth }) {
  return (
    <div style={{ paddingLeft: depth * 16 }}>
      <span style={{ color: depth === 0 ? '#9333ea' : '#555' }}>{'‣ '.repeat(depth === 0 ? 0 : 1)}{node.label}</span>
      {node.children.map((child, i) => (
        <Leaf key={i} node={child} depth={depth + 1} />
      ))}
    </div>
  )
}
